<?php

/**
 * @file
 * Primary module hooks for IBT Entity Label Override module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function ibt_entity_label_override_preprocess_page_title(&$vars) {
  $ibt_entity_label_override_settings = \Drupal::config('ibt_entity_label_override.settings');
  $elo = $ibt_entity_label_override_settings->get('entity-label-overrides');
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($field_label = $elo[$node->getEntityTypeId()][$node->getType()] ?? NULL) {
      if ($node->hasField($field_label) && !$node->get($field_label)->isEmpty()) {
        $vars['title'] = [
          '#type' => 'markup', #@todo use page-title theme function.
          '#markup' => '<span class="field field--name-title field--type-string field--label-hidden">'
            . $node->get($field_label)->getString()
            . '</span>',
        ];
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ibt_entity_label_override_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_state->getFormObject() instanceof \Drupal\node\NodeForm) {
    $node = $form_state->getFormObject()->getEntity();
    if (
      $node instanceof \Drupal\node\NodeInterface
      && str_starts_with($form_id, 'node_')
      && str_contains($form_id, $node->bundle())
    ) {
      $elo = \Drupal::config('ibt_entity_label_override.settings')->get('entity-label-overrides');
      if ($field_label = $elo[$node->getEntityTypeId()][$node->getType()] ?? NULL) {
        if ($node->hasField($field_label)) {
          $form[$field_label]['#attributes']['class'][] = 'field--name-title';
          $form['title']['#access'] = FALSE;
          $submit_handlers = $form['actions']['submit']['#submit'];
          $save_key = array_search('::save', $submit_handlers);
          if ($save_key !== FALSE) {
            array_splice($form['actions']['submit']['#submit'], $save_key, 0, '_entity_label_overrides_handler');
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ibt_entity_label_override_preprocess_node(&$vars) {
  $node = $vars['node'] instanceof \Drupal\node\NodeInterface ? $vars['node'] : NULL;
  $view_mode = $vars['view_mode'];
  if ($view_mode === 'teaser') {
    $elo = \Drupal::config('ibt_entity_label_override.settings')->get('entity-label-overrides');
    if ($field_label = $elo[$node->getEntityTypeId()][$node->getType()] ?? NULL) {
      $vars['label']['#access'] = FALSE;
    }
  }
}

function _entity_label_overrides_handler($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $elo = \Drupal::config('ibt_entity_label_override.settings')->get('entity-label-overrides');
  if ($field_label = $elo[$node->getEntityTypeId()][$node->getType()] ?? NULL) {
    $node->set('title', $form_state->getValue($field_label));
  }
}