<?php

/**
 * @file ibase_mixcloud_media.module
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\media_library\Form\OEmbedForm;
/**
 * Implements hook_media_source_info_alter().
 */
//function ibase_mixcloud_media_source_info_alter(array &$sources) {
//  $sources['oembed'] = [
//    'id' => 'oembed',
//    'label' => new TranslatableMarkup('Mixcloud'),
//    'description' => new TranslatableMarkup('Remote embed code or OEmbed from Mixcloud.'),
//    'allowed_field_types' => ['string'],
//    'default_thumbnail_filename' => 'no-thumbnail.png',
//    'providers' => ['MixCloud', ],
////    'providers' => ['MixCloud', 'SoundCloud',],
//    'class' => 'Drupal\media\Plugin\media\Source\OEmbed',
//    'forms' => [
//      'media_library_add' => OEmbedForm::class,
//    ],
//    'provider' => 'ibase_media_embed',
//  ];
//}
//
///**
// * Implements hook_oembed_resource_data_alter().
// */
//function ibase_mixcloud_media_oembed_resource_data_alter(array &$data, $url) {
//  if (isset($data['provider_name']) && $data['provider_name'] === 'Mixcloud') {
//    $data['provider_name'] = 'MixCloud';
//  }
//  if (isset($data['image'])) {
//    $data['thumbnail_uri'] = $data['image'];
//  }
//}

/**
 * Implements hook_preprocess_HOOK().
 */
function ibase_mixcloud_media_preprocess_field(&$vars) {
  if ($vars['field_name'] === 'field_embed_code' && isset($vars['element']['#items'][0])) {
    $field_item_value = $vars['element']['#items'][0]->getValue();
    $vars['media_embed_code'] = [
      '#type' => 'markup',
      '#markup' => \Drupal\Core\Render\Markup::create($field_item_value['value'] ?? ''),
    ];
  }
}

/**
 * Implements hook_oembed_resource_url_alter().
 */
function ibase_mixcloud_media_oembed_resource_url_alter(array &$parsed_url, \Drupal\media\OEmbed\Provider $provider) {
  $t=1;
}