<?php

/** @file ibase_api.module */

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ibase_api_node_insert(\Drupal\Core\Entity\EntityInterface $entity) {
//  _ibase_api_channel_process($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function ibase_api_node_update(\Drupal\Core\Entity\EntityInterface $entity) {
//  _ibase_api_channel_process($entity);
}

function _ibase_api_channel_process(\Drupal\Core\Entity\EntityInterface $entity) {
//  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'channel') {
//    \Drupal::service('ibase_api.service')->updateChannel($entity->id());
//  }
}