<?php

/**
 * @file
 * Primary module hooks for AK Theme module.
 */

function ak_theme_theme($existing, $type, $theme, $path) {
  return [
    'exhibition_years' => [
      'variables' => [
        'years' => [],
        'title' => NULL,
        'current' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ak_theme_preprocess_menu__main__sidebar_first(&$vars) {
  $nids = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['field_upcoming' => 1, 'status' => 1]);
  if (sizeof($nids) === 0) {
    unset($vars['items']['menu_link_content:9c794a69-6903-4ed6-b03b-a6e46c647acd']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ak_theme_preprocess_block(&$vars) {
  // Add year to copyright block.
  if (isset($vars['plugin_id']) && $vars['plugin_id'] === 'block_content:4b60f217-8746-4af7-a68c-ffcd1c41e75e') {
    $raw = strip_tags($vars["content"]["body"][0]["#text"]);
    $year = date('Y');
    $vars["content"]["body"][0]["#text"] = "$raw$year";
  }

}
