<?php

/**
 * @file
 * Contains goldies_shopify.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function goldies_shopify_taxonomy_term_insert(EntityInterface $entity) {
  Drupal::service('goldies_shopify.utility')->syncShopifyNode($entity, 'collection');
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * Implements hook_ENTITY_TYPE_update().
 */
function goldies_shopify_taxonomy_term_update(EntityInterface $entity) {
  Drupal::service('goldies_shopify.utility')->syncShopifyNode($entity, 'collection');
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function goldies_shopify_shopify_product_insert(EntityInterface $entity) {
  Drupal::service('goldies_shopify.utility')->syncShopifyNode($entity, 'product');
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * Implements hook_ENTITY_TYPE_update().
 */
function goldies_shopify_shopify_product_update(EntityInterface $entity) {
  Drupal::service('goldies_shopify.utility')->syncShopifyNode($entity, 'product');
}
