<?php

/**
 * @file
 * Contains goldies_shopify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_update().
 */
function goldies_shopify_entity_insert(EntityInterface $entity) {
  $t=1;
}

/**
 * Implements hook_entity_update().
 */
function goldies_shopify_entity_update(EntityInterface $entity) {
  $t=1;
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function goldies_shopify_ENTITY_TYPE_update(Drupal\Core\Entity\EntityInterface $entity) {

}
