<?php

/**
 * Implements hook_views_post_execute().
 */
function goldies_retailers_views_post_execute(\Drupal\views\ViewExecutable $view) {
  if ($view->id() === 'retailers') {
    foreach ($view->result as $row) {
      if ((int) $row->_entity->get('field_weight')->getString() !== $row->draggableviews_structure_weight_1) {
        $row->_entity->set('field_weight', $row->draggableviews_structure_weight_1);
        $row->_entity->save();
      }
    }
  }

}