<?php

/**
 * @file
 * Primary module hooks for IBASE forms module.
 */

/**
 * Implements hook_form_alter().
 */
function ibase_forms_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $t=1;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ibase_forms_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form['#id']) {
    case 'views-exposed-form-events-block-main':
    case 'views-exposed-form-news-block-main':
      if (isset($form['pid'])) {
        $form['#attributes']['class'][] = 'the-form-filters';
        $form['#attached']['library'][] = 'the/form-filters';
        $form['pid']['#type'] = 'select';
        $projects = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => 'project', 'status' => 1]);
        $options = [];
        foreach ($projects as $project) {
          $options[$project->id()] = $project->getTitle();
        }
        $form['pid']['#options'] = ['' => t('All projects')] + $options;
        $form['pid']['#size'] = 1;
      }
      break;
  }
}