# Schema for the configuration files of the IBASE gatsby deploy module.
ibase_gatsby_deploy.settings:
  type: config_object
  label: 'IBASE gatsby deploy settings'
  mapping:
    example:
      type: string
      label: 'Example'
